/* Fix Chatter Styles */
.publishercontainer { max-width: 100% !important; }
span.pArrow { margin-left: 0px !important; }
.wrapper { margin: auto !important; box-shadow: initial !important;padding: 0 !important; }
:root .wrapper { /* IE9 */ box-shadow: 0px 0px 0px rgba(0,0,0,0)\9 !important; }

.publisherFeedItemTypeChoices { height: auto !important; }
.feedcontainer { text-align:left; }
.publishercontainer input[type="text"] { width:125px; }
.publishercontainer .contentPublisherSlideDown table.postInput { width: 215px; }
.apexp { width:299px }
.publishercontainer li.publisherFeedItemTypeChoice { margin-right:0px; }

.cxallfeedactions .feeditemActionMenu .zen-options, 
.feedcommentactions .commentActionMenu .zen-options, 
.feedmainandrightbar .feedrightbar .zen-options
{
    left: -140px;
}

.chatterHover>.wrapper { left: -90px; }
/* End Chatter Fix */

.main-content-block
{
    border: 1px solid #83c600;/**/
    background: #666; /* linear-gradient(#ffffff, #83c600) white; */
    box-shadow: 0 1px 3px #83c600;
    border-radius: 3px;
    height: 546px;
}

.main-content-block a
{
    color: #FFF;
    text-decoration:underline;
}

.bottom-content-block
{
    /*
    border-bottom: 2px solid #83c600;
    background: linear-gradient(#ffffff, #a7a9ac) white; 
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
    border-right: 2px solid #83c600;
    border-left: 2px solid #83c600;
    border-top: solid 2px #83c600;
    border-radius: 3px;
    */
}

.main-content-block li, .main-content-block p
{
    color: #DDD; /*#555;*/
    font-size: 1.2em;
}

.page-photo
{
    /* border:solid 1px #DDD; */
    /* box-shadow: 0 1px 3px #DDD; */
    width: 660px;
}

.right-panel
{
    float:right; 
    width:200px; 
    margin-left:10px; 
    margin-bottom:0px;
}

.team-page-header-text
{
    margin-top: 20px;
    margin-bottom: 10px;
    color: #83c600;
    font-size: 20pt;
}

.team-page-heading-text
{
    color: #83c600;
    font-size: 18pt;
}

.min-height
{
    min-height: 340px;
}