.portal p {
    font: 12px/1.5 "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    color: #666;
    text-align:left;
    margin-top:0;
}

.portal h1 {
    font-family: "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    font-weight:normal;
    font-size:20px;
    margin: 0;
    padding: 0;
    color:#666;
    text-align:left;
    font-weight:500;
    display:inherit !important;
}

.portal h2 {
    font: 18px/1.5 "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    color:#fff;
    padding: 0;
    margin:0 20px 0 0;
    position:relative;
    text-align:right;
    top:90px;
    display:inherit !important;
}

.portal h3 {
    font: 500 16px/1.5  "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    margin: 10px 0;
    padding:0;
    color:#666;
    text-align:left;
    line-height:112%;
    display:inherit !important;
}

.portal ul {
    list-style-type:none;
    margin-top:0;    
    padding:0;
    text-align:left;
    display:inherit !important;
}

.portal ul li {
    margin-left:0;
}

.portal a {
    font: 12px/1.5 "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    font-weight:bold;
    text-decoration: none;
    color: #336633;
    padding-left:0;
}

.portal a:hover {	
    text-decoration: underline;
    color: #81bd00;
}

.portal hr {
    border-top: 0;
    border-left: 0;
    border-right: 0;
    border-bottom: 1px solid #666;
}

.highlight {
    color: #cc092f;
}

.assoc-portal ul{
    margin: 10px 0;
}

.assoc-portal ul p {
    font-family: "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    font-size: 12px;
    font-weight: 400;
    color: #666;
    line-height: 1.5em;
}

.assoc-portal ul li{
    font-family: "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    font-size: 12px;
    font-weight: 400;
    color: #666;
    line-height: 1.5em;
}

.assoc-portal ul li a{
    font-family: "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    font-size: 12px;
    font-weight: bold;
    color: #336633;
    line-height: 1.5em;
}
.fix_chatter{
   max-height:600px;
   overflow-y:scroll;
   box-shadow: 2px 2px 4px #D5D0D0; 
    
}
#wrapper-body {
    margin: 0px auto; 
    padding: 0; 
    background-color: #666; 
    max-width: 1080px; 
    margin-top: 16px;
}

#container {
    margin: 0px auto; 
    padding: 0 0 25px 0; 
    background: #fff; 
    border: 0 2px 2px 2px solid #e3e3e3; 
    max-width: 1000px; 
}

/*  NAVIGATION  */

#nav-container {
    width: 960px;
    margin: auto 0;
    min-height: 40px;
    background-color: #000;
}

#nav ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
}

#nav li {
    float: left;        
}

#nav a {
    display: block;
    width: 137px;
    background-color: #000;
    text-align:center;
    padding:8px 0;
    font-family: "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    font-weight:400;
    font-style:normal;
    font-size:17px;
    color:#fff;
}

#nav a:active {
    background-color: #81bd00;
}

#sub-nav-container {
    width: 960px;
    min-height: 40px;
    background-color: #666;
}

#sub-nav ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
}

#sub-nav li {
    float: left;
    height:40px;
}

#sub-nav a {
    display: block;
    min-width: 120px;
    height: 24px;
    background-color: #666;
    text-align: center;
    padding: 8px 0;
    font-family: "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    font-weight: 400;
    font-style: normal;
    font-size: 17px;
    color: #fff;
    text-decoration: inherit;
}


/*  SECTIONS  */

#content {
    width: 920px;
    min-height: 250px;
}

#footer {
    max-width: 815px;
    text-align:left;
    color: #fff;
    border: 1px solid #e3e3e3; 
    margin-top: 20px;
    padding: 20px 20px 20px 25px;
    background: #fff;
}

.section {
    clear: both;
    padding: 0px;
    margin: auto 0;
    max-width: 1000px;
    background: url('/Employees/resource/1410547953000/EMP_green_white_bottom');
    background-repeat: repeat-x;
}

.section-banner {
    clear: both;
    padding: 0px;
    margin: -16px 0 0 0;
    max-width: 100%;
    min-height: 276px;
    background-color: #81bd00;
}

.section-banner-sub {
    clear: both;
    padding: 0px;
    margin: -16px 0 0 0;
    max-width: 100%;
    min-height: 140px;
    background-color: #81bd00;
}

.home-content-details {
    margin-top: 10px;
    margin-bottom: 5px;
}

.section-banner-sub-Home-details {
    background-repeat: no-repeat; 
    background-position: 40px center; 
    height: 300px;
}

.section-banner-sub-details {
    background-repeat: no-repeat; 
    background-position: 40px center; 
    height: 200px;
}

.span_Align_Text {
    text-align:left !important;
}

/*  COLUMN SETUP  */

.col {
    display: block;
    margin: 0 0 0 1%;
}

.col:first-child { 
    margin-left: 0; 
}

.col li {
    padding-bottom: 4px;
}

/*  GRID OF THREE  */

.three_col {
    width: 30%;
    float: left;
    min-height: 250px; /* Changed to 250 from 225 by Lalitha Adduru on 23/02/2015 */
    padding-left: 1.333%;
    padding-bottom: 1.333%;
    padding-right: 1.333%;
    margin-bottom: 10px;
}

.span_3_of_3 {
    background-color: #ebebeb;
}

.span_2_of_3 {
    background-color: #e0e0e0;
}

.span_1_of_3 {
    padding-right: 0.1%;     /* Added by Lalitha Adduru on 23/02/2015 */
    padding-top: 0%;		/* Added by Lalitha Adduru on 23/02/2015 */
    background-color: #ccc;
}

.span_combine_2col {
    float: left;  
    min-height: 225px;
    width: 60%;
    text-align: left;
    background-color: #e0e0e0;
}

.span_combine_2col_Content {
    padding: 10px;
}

.span_combine_3col {
    float: left;  
    min-height: 225px;
    text-align: left;
    height: 300px;
    overflow: auto;
    background-color: #e0e0e0;
    width: 97.34%;
    padding: 1.33%;
}

.span_3_of_3_MultiRow {
    float: left;
    min-height: 225px;
    width: 39%;
    text-align: left;    
}

.span_3_of_3_MultiRow_Content:first-child {
    margin-top: 0;
}

.span_3_of_3_MultiRow_Content {
    margin-top: 10px;
    padding: 10px;
    background-color: #ebebeb;
}

.span_combine_2Multi {
	float: left;  
	min-height: 225px;
	width: 60%;
	text-align: left;          
}
.span_combine_2colMulti_Content:first-child {
	margin-top: 0;
}

.span_combine_2colMulti_Content {
	margin-top:10px;
	padding: 10px;
	background-color: #e0e0e0;
	margin-left:0px;
}

.hideComponent {
	display:none !important;
}
/*  GRID OF THREE NO BACKGROUND 3 NARROW COLUMNS NO BACKGROUND  */

.span_nobkg {
    float: left;
    border: none;
    background-color: transparent;
    min-height: 225px;
    padding: 25px 0 0 15px;
    
}

.span_3_of_3_nobkg {
    width: 34%;
    margin: 0 8px 45px 8px;
}

.span_2_of_3_nobkg {
    width: 28%;
    margin: 0 8px 0 8px;
}

.span_1_of_3_nobkg {
    width: 28%;
    margin: 0 8px 0 8px;
}

/* css for read all*/
.span_3_of_3_nobkg_readAll {
    width: 100%;
    float: left;
    margin: 0 8px 45px 8px;
    border: none;
    padding: 25px 0 0 15px;
    min-height: 225px;
    background-color: transparent;
}

.tool-list li {
    list-style-type:disc;
    color:#81bd00;
    margin-left:15px !important;
}

:root .section { /* IE9 */ 
    margin-top: -12px\9;
}

/* css for career content page */
.career_container {
    text-align:left;
    font: 12px/1.5 "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    color: #666;
}

.career_span {
    margin-right:10px;
}

.career_ul {
    list-style-type:disc !important;
    margin-left:70px;
}

.career_link {
    font-weight: bold !Important;
}

.career_span_head {
    color:#81bd00;
    font-weight:bold;
    font-size: 20px;
}

/* css for portal hub*/
.policyContainer {
    text-align:left;
}

.policy_header {
    font-weight:bold;
    margin-bottom:10px;
    font-size:16px;
}

.policy_subheader {
    font-weight:bold;
    margin-bottom:10px;
    font-size:14px
}

.policy_link {
	font: 12px/1.5 "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, "Open Sans", sans-serif;
    text-decoration:none;
    float:left;
	color: #336633 !important;
	font-weight:bold;
}

.policy_link:hover {	
    text-decoration: underline;
    color: #81bd00 !important;
}

.policy_col_1 {
    width:80%;
}

.policy_col_2 {
    width:20%;
}

/* css for  leadership*/
.leadership_li {
    height:55px;
}

.leadership_image {
    width: 50x;
    height: 55px;
    float:left;
    margin-right:5px;
}

.leadership_date {
    float:right;
    margin-right:10px;
}

.leadership_ReadAll {
    color:#336179;
}

/* company announcement css */
.company_date {
    font: 12px/1.5 Helvetica, sans-serif;
    font-weight:bold;
}

/* steve message css */
.steve_container {
    float:right; 
    width:115px;
    margin-left:5px;
    margin-bottom:0px;
}

.steve_content {
    text-align: justify !important;
    text-justify: inter-word !important;
    padding-right:10px
}

/* acknowledgement css */
.acknowledgement_disabled {
    color: #5c73ac;
}

.acknowledgement_Field {
    font-weight:normal;
}

.acknowledgement_Link {
    text-decoration:none;
    float:left;
}

.acknowledgement_Table {
    text-align:center;
}

.ack-disabled {
    display: none !important;
}

.noSidebarCell, .sidebarCell .fixed	
{
	padding: 0px !important;
}
	
/* css for table */
.table_myinfo td {
    color: #666 !important;
}

/* Immigration */
.immigration_header {
	font-size: 18px;
}

.immigration_content {
	line-height:17px;
}

.immigration_contentHighlight {
	color:#81bd00;
	font-weight:bold;
}

.immigration_table_header {
	font-size: 16px;
	font-weight:bold;
}

/*09 Feb 2014 Hemanth Added styles for group links */
.groupLinks {
    max-width: 1000px;
    display: block;
    width: 920px;
    background-color: #ccc;
}

.groupLinks h3{
    font-weight:bold;
    padding-left:30px;
}

.groupLinks a {
    padding-top: 10px;
    padding-left: 0px;
}

.groupLinks li {
    list-style-type: disc;
    margin-left: 60px !important;
    color: #81bd00;
}

/*  GO FULL WIDTH AT LESS THAN 480 PIXELS */

@media only screen and (max-width: 480px) {
    .col { 
        margin: 1% 0 1% 0%;
    }
}

@media only screen and (max-width: 480px) {
    .span_3_of_3 {
        width: 98%;
        
    }
    .span_2_of_3 {
        width: 98%;
        
    }
    .span_1_of_3 {
        width: 98%;
        
    }
    
    .span_1_of_2 {
        width: 95%;
        padding:10px;
        
    }
    .span_2_of_2 {
        width: 95%;
        
    }
    
}

@media only screen and (max-width: 480px) {
    #wrapper-body h2 { 
        top:110px;
    }
}   
@media only screen and (max-width: 480px) {
    #wrapper { 
        padding:18px;
    }
}
/* Css hack for IE */
@media all and (-ms-high-contrast:none)
    {
    .section { margin-top: -12px; } /* IE10 */
    #content { margin-top: -12px; }
    *::-ms-backdrop, .section { margin-top: -12px; } /* IE11 */
    *::-ms-backdrop, #content { margin-top: -12px; } /* IE11 */
}