public class DS_SystemAtDealerShipInsertTest {
	/*
    testMethod static void testSystemAtDealerShipInsert(){
    	Account acct = new Account(Name='Audi of Bensenville');
    	insert acct;
		Systems__c sys = new Systems__c(Name='ADP RON ASP');
			sys.SLXVendor_Id__c = 'RONADP123456';
			sys.SLXSystem_Id__c = 'RONADP987654';
			sys.Type__c = 'DMS';
		insert sys;
		System_at_Dealership__c dealerSys = new System_at_Dealership__c(Name='ID - 11111');
			dealerSys.Account__c = acct.Id;
			dealerSys.Vendor__c = sys.Id;
			dealerSys.Install_Date__c = Date.ValueOf('2009-01-27');
			dealerSys.System_Type__c = 'DMS';
			dealerSys.SLX_Vendor_ID__c = sys.SLXVendor_Id__c;
			dealerSys.SLX_Sys_ID__c = sys.SLXSystem_Id__c;
		insert dealerSys;
		Systems__c sys1 = new Systems__c(Name='ADP RON 9500');
			sys1.SLXVendor_Id__c = 'RONADP012345';
			sys1.SLXSystem_Id__c = 'RONADP098765';
			sys1.Type__c = 'DMS';
		insert sys1;
		System_at_Dealership__c dealerSys1 = new System_at_Dealership__c(Name='ID - 22222');
			dealerSys1.Account__c = acct.Id;
			dealerSys1.Vendor__c = sys1.Id;
			dealerSys1.Install_Date__c = Date.ValueOf('2009-01-28');
			dealerSys1.System_Type__c = 'DMS';
			dealerSys1.SLX_Vendor_ID__c = sys1.SLXVendor_Id__c;
			dealerSys1.SLX_Sys_ID__c = sys1.SLXSystem_Id__c;
		insert dealerSys1;
    }
    */
}