/*------------------------------------------------------------
Author: Alex Daria
Company: Cloud Sherpas       
Description: Controller for the IMP_IncrementMilestoneDelayedCounterField trigger,  Update the milestone delayed count field
Test Class: IMP_IncrementMilestoneCounter_Test
History
09/16/14    Alex Daria          Created
------------------------------------------------------------*/
public class IMP_IncrementMilestoneCounter_Handler
{
    
}