//2015-09-22- anirudh.singh@cdk.com- To upgrade the API Version FROM 28.0 to 34.0.
//2016-02-22- anirudh.singh@cdk.com- Commented this class due to naming standards issue.
@IsTest
public class CB_WebIDAccountTeamMembersBatchTest
{
    /*public static testmethod void ProcessBatch()
    {
        CB_WebIDAccountTeamMembers_Test.SetupSettings();
        
        CB_WebIDAccountTeamMembersBatch b1=new CB_WebIDAccountTeamMembersBatch();
        
        Account a=DS_TestObjects.NewAccount_Inserted();
        CB_WebIDAccountTeamMembersBatch b2=new CB_WebIDAccountTeamMembersBatch(new List<Account>{a});
        
        String query=b1.st();
        
        List<Account> Accounts=Database.query(query);
        b1.ex(Accounts);
        
        //2015-11-17- anirudh.singh@cdk.com- Changed fn to finish.
        b1.finish(null);
    }*/
}